### ISSUE TITLE
Set up a development environment

### ISSUE THREAD

**Issue by kkhys** [kkhys/me#1]
Do only the minimum settings.

# TODO

## Development Support Tools

- [x] .gitignore (https://github.com/kkhys/me/pull/2/commits/d85c2dd714b05d304e2f53628538f51bccfb1758)
- [x] README (https://github.com/kkhys/me/pull/2/commits/d04b61084f54333264b064039e4747ee0544119e)
- [x] LICENSE (https://github.com/kkhys/me/commit/420b404ee020fa23031dcb5c0005c669dd738fd6)
- [x] pnpm (https://github.com/kkhys/me/commit/f9ae1ac14646e13c72b613ec6e60d58e6156166e)
- [x] commitizen (https://github.com/kkhys/me/commit/1c8fcdfbcd92ee053eca6f4dccce38af6224bf7f)
- [x] editorconfig (https://github.com/kkhys/me/commit/b317e4da8384a49838f2a6a2983194e5f4fe8c53)
- [x] prettier (https://github.com/kkhys/me/commit/2248318ee57800ecd8e863c0566cf89f2e5821f7)
- [x] tsconfig (https://github.com/kkhys/me/commit/a7b6afaced0ae09e68974a7ec90236d2f473c004)
- [x] eslint (https://github.com/kkhys/me/commit/f96bc9b0733a772c64296d9e885fcaf8fe2fe81e)
- [x] tailwind (https://github.com/kkhys/me/commit/c1ce7afbaf1cf5cd2cdc44b9e1e3a9ebd3e1bdd0)
- [x] turbo generator (https://github.com/kkhys/me/commit/3d2ac71fec1fd817451f805349253caf6a67f203)
- [x] husky (https://github.com/kkhys/me/commit/3987969d725822549f4dc7b8f899436a6cef270c
- [x] commitlint (https://github.com/kkhys/me/commit/722601f865b56b257d63a9b92169ff13577f59c8)
- [x] issue templates (https://github.com/kkhys/me/commit/9dcb388295ed9aca22cbf2195695c6cbfb995a06)
- [x] renovate (https://github.com/kkhys/me/commit/6ecdf8b843a82ad1a4f754434a7354481bf56859)
- [x] github-label-sync (https://github.com/kkhys/me/commit/e692ed4c324985c5e81fc75e5dd1b5fd51837416)

## Web Libraries

- [x] Turborepo (https://github.com/kkhys/me/commit/b317e4da8384a49838f2a6a2983194e5f4fe8c53)
- [x] Next.js (web) (https://github.com/kkhys/me/commit/bf5046bd09b0089326bc32e3c99f790e7cbed6af)
- [x] Next.js (admin) (https://github.com/kkhys/me/commit/1a713a4f6d5831cc36d4c37744182e79e9fd5938)
- [x] Storybook (https://github.com/kkhys/me/commit/66281f98d91d76ebb198ca59ff05945ab7ea7eed)
